---
Name: catalogmanager
---

Page:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CategoryPageHierarchyExtension

SilverStripe\SiteConfig\SiteConfig:
  required_permission:
    - SITETREE_VIEW_ALL
    - SITETREE_EDIT_ALL
